import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { StyleSheet, Text, View } from "react-native";

type PreviewColors = { background: string; surface: string; text: string; muted: string; border: string; primary: string };

export function AccessibilityLibraryPreview({ colors, isRTL, textScaleMultiplier, lineHeightMultiplier, fontWeight, fontFamily, title, detail, label }: { colors: PreviewColors; isRTL: boolean; textScaleMultiplier: number; lineHeightMultiplier: number; fontWeight: "400" | "600" | "700"; fontFamily?: "OpenDyslexic-Regular"; title: string; detail: string; label: string }) {
  const scaled = (value: number) => Math.round(value * textScaleMultiplier);
  const direction = isRTL ? "row-reverse" : "row";
  const align = isRTL ? "right" : "left";
  return <View accessibilityLabel={label} style={[styles.card, { backgroundColor: colors.background, borderColor: colors.border }]}><View style={[styles.header, { flexDirection: direction }]}><Text style={[styles.label, { color: colors.muted, fontSize: scaled(9), lineHeight: Math.round(scaled(13) * lineHeightMultiplier), fontWeight, fontFamily }]}>{label}</Text><MaterialIcons name="search" size={18} color={colors.primary} /></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border, flexDirection: direction }]}><MaterialIcons name="search" size={15} color={colors.muted} /><Text style={[styles.searchText, { color: colors.muted, fontSize: scaled(10), lineHeight: Math.round(scaled(15) * lineHeightMultiplier), fontWeight, fontFamily }]}>{detail}</Text></View><View style={[styles.row, { flexDirection: direction }]}><View style={[styles.cover, { backgroundColor: colors.primary }]}><MaterialIcons name="music-note" size={18} color={colors.background} /></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.title, { color: colors.text, textAlign: align, fontSize: scaled(13), lineHeight: Math.round(scaled(19) * lineHeightMultiplier), fontWeight, fontFamily }]}>{title}</Text><Text numberOfLines={1} style={[styles.detail, { color: colors.muted, textAlign: align, fontSize: scaled(10), lineHeight: Math.round(scaled(15) * lineHeightMultiplier), fontWeight, fontFamily }]}>{detail}</Text></View><MaterialIcons name="more-vert" size={18} color={colors.muted} /></View></View>;
}

const styles = StyleSheet.create({ card: { marginTop: 10, padding: 12, borderRadius: 20, borderWidth: 2 }, header: { alignItems: "center", justifyContent: "space-between" }, label: { flex: 1, letterSpacing: 0.8 }, search: { marginTop: 10, borderRadius: 11, borderWidth: 1, alignItems: "center", gap: 6, paddingHorizontal: 9, paddingVertical: 7 }, searchText: { flex: 1 }, row: { marginTop: 10, alignItems: "center", gap: 9 }, cover: { width: 40, height: 40, borderRadius: 10, alignItems: "center", justifyContent: "center" }, copy: { flex: 1, minWidth: 0 }, title: { fontWeight: "700" }, detail: { marginTop: 1 } });
