import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { StyleSheet, Text, View } from "react-native";

type PreviewColors = { background: string; surface: string; text: string; muted: string; border: string; primary: string };

export function AccessibilityPlayerPreview({ colors, isRTL, textScaleMultiplier, fontWeight, title, detail, label }: { colors: PreviewColors; isRTL: boolean; textScaleMultiplier: number; fontWeight: "400" | "600" | "700"; title: string; detail: string; label: string }) {
  const scaled = (value: number) => Math.round(value * textScaleMultiplier);
  const direction = isRTL ? "row-reverse" : "row";
  const align = isRTL ? "right" : "left";
  return <View accessibilityLabel={label} style={[styles.card, { backgroundColor: colors.background, borderColor: colors.border }]}><View style={[styles.top, { flexDirection: direction }]}><MaterialIcons name={isRTL ? "keyboard-arrow-right" : "keyboard-arrow-left"} size={18} color={colors.muted} /><Text style={[styles.label, { color: colors.muted, fontSize: scaled(9), lineHeight: scaled(13), fontWeight }]}>{label}</Text><MaterialIcons name="more-horiz" size={18} color={colors.muted} /></View><View style={[styles.art, { backgroundColor: colors.primary }]}><MaterialIcons name="graphic-eq" size={38} color={colors.background} /></View><View style={styles.copy}><Text numberOfLines={1} style={[styles.title, { color: colors.text, textAlign: align, fontSize: scaled(15), lineHeight: scaled(21), fontWeight }]}>{title}</Text><Text numberOfLines={1} style={[styles.detail, { color: colors.muted, textAlign: align, fontSize: scaled(10), lineHeight: scaled(15), fontWeight }]}>{detail}</Text></View><View style={[styles.progress, { backgroundColor: colors.border }]}><View style={[styles.progressFill, { backgroundColor: colors.primary }]} /></View><View style={[styles.controls, { flexDirection: direction }]}><MaterialIcons name="skip-previous" size={25} color={colors.text} /><View style={[styles.play, { backgroundColor: colors.primary }]}><MaterialIcons name="play-arrow" size={25} color={colors.background} /></View><MaterialIcons name="skip-next" size={25} color={colors.text} /></View></View>;
}

const styles = StyleSheet.create({ card: { marginTop: 10, padding: 12, borderRadius: 20, borderWidth: 2 }, top: { alignItems: "center", justifyContent: "space-between" }, label: { flex: 1, textAlign: "center", letterSpacing: 0.8 }, art: { height: 126, borderRadius: 16, marginTop: 10, alignItems: "center", justifyContent: "center" }, copy: { marginTop: 10 }, title: { fontWeight: "700" }, detail: { marginTop: 1 }, progress: { height: 4, borderRadius: 4, overflow: "hidden", marginTop: 11 }, progressFill: { width: "42%", height: "100%", borderRadius: 4 }, controls: { alignItems: "center", justifyContent: "center", gap: 22, marginTop: 11 }, play: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" } });
