import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { TrackRow } from "@/components/omniwave/track-row";
import { CollectionSkeleton } from "@/components/omniwave/content-skeleton";
import { Reveal } from "@/components/omniwave/reveal";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/omniwave/player-store";
import { useThemeContext } from "@/lib/theme-provider";
import type { Playlist, Track } from "@/lib/omniwave/types";

type ListItem = { type: "playlist"; playlist: Playlist } | { type: "track"; track: Track };

export function PlaylistsScreen() {
  const { playlists, tracks, currentTrack, playTrack, toggleFavorite, createPlaylist, renamePlaylist, movePlaylist, addTrackToPlaylist, removeTrackFromPlaylist, isReady } = usePlayer();
  const { theme, isRTL, t, textScaleMultiplier } = useThemeContext();
  const [editorMode, setEditorMode] = useState<"create" | "rename" | null>(null);
  const [draftName, setDraftName] = useState("");
  const [selectedPlaylistId, setSelectedPlaylistId] = useState<string | null>(null);
  const selectedPlaylist = playlists.find((playlist) => playlist.id === selectedPlaylistId) ?? null;
  const selectedTracks = useMemo(() => selectedPlaylist?.trackIds.map((id) => tracks.find((track) => track.id === id)).filter((track): track is Track => Boolean(track)) ?? [], [selectedPlaylist, tracks]);
  const listItems = useMemo<ListItem[]>(() => selectedPlaylist ? selectedTracks.map((track) => ({ type: "track", track })) : playlists.map((playlist) => ({ type: "playlist", playlist })), [playlists, selectedPlaylist, selectedTracks]);
  const openCreate = () => { setDraftName(""); setEditorMode("create"); };
  const openRename = () => { if (!selectedPlaylist) return; setDraftName(selectedPlaylist.name); setEditorMode("rename"); };
  const savePlaylist = () => { if (!draftName.trim()) return; if (editorMode === "rename" && selectedPlaylist) renamePlaylist(selectedPlaylist.id, draftName); else createPlaylist(draftName); setDraftName(""); setEditorMode(null); };
  const align = isRTL ? "right" : "left";
  const direction = isRTL ? "row-reverse" : "row";
  const scaled = (value: number) => Math.round(value * textScaleMultiplier);

  if (!isReady) return <ScreenContainer className="px-5"><CollectionSkeleton variant="playlists" /></ScreenContainer>;

  return <ScreenContainer className="px-5"><FlatList data={listItems} keyExtractor={(item) => item.type === "track" ? item.track.id : item.playlist.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View>
    <Reveal><View style={[styles.topLine, { flexDirection: direction }]}>{selectedPlaylist ? <Pressable accessibilityLabel={t("close")} onPress={() => setSelectedPlaylistId(null)} style={({ pressed }) => [styles.roundButton, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, pressed && styles.pressed]}><MaterialIcons name={isRTL ? "arrow-forward" : "arrow-back"} size={21} color={theme.colors.text} /></Pressable> : <Pressable accessibilityLabel={t("newPlaylist")} onPress={openCreate} style={({ pressed }) => [styles.roundButton, { backgroundColor: theme.colors.primary, borderColor: theme.colors.primary }, pressed && styles.buttonPressed]}><MaterialIcons name="add" size={22} color={theme.colors.onPrimary} /></Pressable>}<View style={styles.headingCopy}><Text style={[styles.eyebrow, { color: theme.colors.secondary, textAlign: align, fontSize: scaled(10), lineHeight: scaled(15) }]}>{selectedPlaylist ? t("playlistDetails") : t("organizeMood")}</Text><Text style={[styles.heading, { color: theme.colors.text, textAlign: align, fontSize: scaled(29), lineHeight: scaled(38) }]}>{selectedPlaylist ? selectedPlaylist.name : t("playlistsTitle")}</Text></View>{selectedPlaylist ? <Pressable accessibilityRole="button" accessibilityLabel={t("renamePlaylist")} onPress={openRename} style={({ pressed }) => [styles.roundButton, { backgroundColor: theme.colors.surfaceMuted, borderColor: theme.colors.border }, pressed && styles.pressed]}><MaterialIcons name="edit" size={20} color={theme.colors.secondary} /></Pressable> : <View style={styles.roundButtonPlaceholder} />}</View></Reveal>
    {selectedPlaylist ? <View style={[styles.detailCard, { backgroundColor: theme.colors.surface, borderColor: `${theme.colors.secondary}66` }]}><View style={[styles.detailTop, { flexDirection: direction }]}><View style={[styles.detailArt, { backgroundColor: theme.colors.secondary }]}><MaterialIcons name="queue-music" size={27} color={theme.colors.onPrimary} /></View><View style={styles.detailCopy}><Text style={[styles.detailTitle, { color: theme.colors.text, textAlign: align }]}>{selectedTracks.length} {t("tracks")}</Text><Text style={[styles.detailText, { color: theme.colors.muted, textAlign: align }]}>{t("queue")}</Text></View></View>{currentTrack ? <Pressable onPress={() => addTrackToPlaylist(selectedPlaylist.id, currentTrack.id)} style={({ pressed }) => [styles.addTrack, { backgroundColor: theme.colors.primary, flexDirection: direction }, pressed && styles.buttonPressed]}><Text style={[styles.addTrackText, { color: theme.colors.onPrimary }]}>{t("addCurrentTrack")}</Text><MaterialIcons name="playlist-add" size={19} color={theme.colors.onPrimary} /></Pressable> : null}</View> : <View style={[styles.overviewCard, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, flexDirection: direction }]}><View style={[styles.overviewIcon, { backgroundColor: `${theme.colors.secondary}22` }]}><MaterialIcons name="auto-awesome" size={21} color={theme.colors.secondary} /></View><View style={styles.overviewCopy}><Text style={[styles.overviewTitle, { color: theme.colors.text, textAlign: align }]}>{t("playlistsTitle")}</Text><Text style={[styles.overviewText, { color: theme.colors.muted, textAlign: align }]}>{t("organizeMood")}</Text></View></View>}
    <Text style={[styles.countLabel, { color: theme.colors.muted, textAlign: align, fontSize: scaled(11), lineHeight: scaled(16) }]}>{selectedPlaylist ? t("tracks") : `${playlists.length} ${t("playlistsCount")}`}</Text>
  </View>} renderItem={({ item, index }) => item.type === "track" ? <TrackRow track={item.track} active={item.track.id === currentTrack?.id} onPress={() => playTrack(item.track)} onFavorite={() => toggleFavorite(item.track.id)} trailing={<Pressable accessibilityLabel={t("remove")} onPress={() => selectedPlaylist && removeTrackFromPlaylist(selectedPlaylist.id, item.track.id)} style={({ pressed }) => [styles.removeButton, pressed && styles.pressed]}><MaterialIcons name="remove-circle-outline" size={22} color={theme.colors.muted} /></Pressable>} /> : <Pressable onPress={() => setSelectedPlaylistId(item.playlist.id)} style={({ pressed }) => [styles.playlistCard, { flexDirection: direction }, pressed && styles.pressed]}><View style={[styles.playlistArt, { backgroundColor: item.playlist.id === "night-drive" ? theme.colors.secondary : theme.colors.primary }]}><MaterialIcons name="queue-music" size={27} color={theme.colors.onPrimary} /></View><View style={styles.playlistCopy}><Text style={[styles.playlistName, { color: theme.colors.text, textAlign: align, fontSize: scaled(15), lineHeight: scaled(21) }]}>{item.playlist.name}</Text><Text style={[styles.playlistMeta, { color: theme.colors.muted, textAlign: align, fontSize: scaled(12), lineHeight: scaled(17) }]}>{item.playlist.trackIds.length} {t("tracks")}</Text></View><View style={[styles.playlistActions, { flexDirection: direction }]}><Pressable accessibilityRole="button" accessibilityLabel={t("moveUp")} disabled={index === 0} onPress={(event) => { event.stopPropagation(); movePlaylist(item.playlist.id, -1); }} style={({ pressed }) => [styles.smallAction, index === 0 && styles.disabledAction, pressed && styles.pressed]}><MaterialIcons name="arrow-upward" size={17} color={theme.colors.muted} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t("moveDown")} disabled={index === playlists.length - 1} onPress={(event) => { event.stopPropagation(); movePlaylist(item.playlist.id, 1); }} style={({ pressed }) => [styles.smallAction, index === playlists.length - 1 && styles.disabledAction, pressed && styles.pressed]}><MaterialIcons name="arrow-downward" size={17} color={theme.colors.muted} /></Pressable></View><MaterialIcons name={isRTL ? "chevron-left" : "chevron-right"} size={20} color={theme.colors.muted} /></Pressable>} ItemSeparatorComponent={() => <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />} ListEmptyComponent={selectedPlaylist ? <View style={styles.empty}><View style={[styles.emptyIcon, { backgroundColor: theme.colors.surfaceMuted }]}><MaterialIcons name="playlist-add" size={28} color={theme.colors.muted} /></View><Text style={[styles.emptyTitle, { color: theme.colors.text, fontSize: scaled(15), lineHeight: scaled(21) }]}>{t("quietPlaylist")}</Text><Text style={[styles.emptyText, { color: theme.colors.muted, fontSize: scaled(12), lineHeight: scaled(18) }]}>{t("addCurrentTrack")}</Text></View> : null} />
    <Modal visible={Boolean(editorMode)} transparent animationType="fade" onRequestClose={() => setEditorMode(null)}><View style={styles.modalBackdrop}><View style={[styles.modalCard, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border, alignItems: isRTL ? "flex-end" : "flex-start" }]}><View style={[styles.modalMark, { backgroundColor: theme.colors.primary }]}><MaterialIcons name={editorMode === "rename" ? "edit" : "queue-music"} size={25} color={theme.colors.onPrimary} /></View><Text style={[styles.modalTitle, { color: theme.colors.text, textAlign: align }]}>{editorMode === "rename" ? t("renamePlaylist") : t("newPlaylist")}</Text><Text style={[styles.modalText, { color: theme.colors.muted, textAlign: align }]}>{t("organizeMood")}</Text><TextInput value={draftName} onChangeText={setDraftName} autoFocus placeholder={t("playlistName")} placeholderTextColor={theme.colors.muted} returnKeyType="done" onSubmitEditing={savePlaylist} style={[styles.nameInput, { color: theme.colors.text, borderColor: theme.colors.border, backgroundColor: theme.colors.surfaceMuted, textAlign: align }]} /><View style={[styles.modalActions, { flexDirection: direction }]}><Pressable onPress={() => setEditorMode(null)} style={({ pressed }) => [styles.cancel, pressed && styles.pressed]}><Text style={[styles.cancelText, { color: theme.colors.muted }]}>{t("cancel")}</Text></Pressable><Pressable onPress={savePlaylist} style={({ pressed }) => [styles.confirm, { backgroundColor: theme.colors.primary }, pressed && styles.buttonPressed]}><Text style={[styles.confirmText, { color: theme.colors.onPrimary }]}>{editorMode === "rename" ? t("saveChanges") : t("savePlaylist")}</Text></Pressable></View></View></View></Modal>
  </ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 12, paddingBottom: 132 }, topLine: { justifyContent: "space-between", alignItems: "center", marginBottom: 20 }, headingCopy: { flex: 1 }, eyebrow: { fontSize: 10, lineHeight: 15, fontWeight: "900", letterSpacing: 1.8 }, heading: { fontSize: 29, lineHeight: 38, fontWeight: "900" }, roundButton: { width: 43, height: 43, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 1 }, roundButtonPlaceholder: { width: 43, height: 43 },
  overviewCard: { alignItems: "center", gap: 12, padding: 15, borderRadius: 22, borderWidth: 1 }, overviewIcon: { width: 43, height: 43, borderRadius: 14, alignItems: "center", justifyContent: "center" }, overviewCopy: { flex: 1 }, overviewTitle: { fontSize: 14, lineHeight: 20, fontWeight: "900" }, overviewText: { fontSize: 11, lineHeight: 17, marginTop: 2 }, countLabel: { fontSize: 11, lineHeight: 16, fontWeight: "900", letterSpacing: 1.2, marginTop: 23, marginBottom: 2 },
  playlistCard: { minHeight: 80, alignItems: "center", gap: 10, paddingVertical: 10 }, playlistArt: { width: 58, height: 58, borderRadius: 18, alignItems: "center", justifyContent: "center" }, playlistCopy: { flex: 1, minWidth: 0 }, playlistName: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, playlistMeta: { fontSize: 12, lineHeight: 17, marginTop: 2 }, playlistActions: { alignItems: "center", gap: 0 }, smallAction: { width: 30, height: 30, alignItems: "center", justifyContent: "center", borderRadius: 15 }, disabledAction: { opacity: 0.3 }, divider: { height: StyleSheet.hairlineWidth },
  detailCard: { padding: 15, borderRadius: 22, borderWidth: 1 }, detailTop: { alignItems: "center", gap: 12 }, detailArt: { width: 48, height: 48, borderRadius: 16, alignItems: "center", justifyContent: "center" }, detailCopy: { flex: 1 }, detailTitle: { fontSize: 14, lineHeight: 20, fontWeight: "900" }, detailText: { fontSize: 11, lineHeight: 17, marginTop: 2 }, addTrack: { minHeight: 40, marginTop: 15, borderRadius: 13, alignItems: "center", justifyContent: "center", gap: 5 }, addTrackText: { fontSize: 12, lineHeight: 17, fontWeight: "900" }, removeButton: { width: 40, height: 40, borderRadius: 20, alignItems: "center", justifyContent: "center" },
  empty: { paddingVertical: 54, alignItems: "center" }, emptyIcon: { width: 54, height: 54, borderRadius: 18, alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900", marginTop: 14 }, emptyText: { fontSize: 12, lineHeight: 18, marginTop: 3 }, pressed: { opacity: 0.68 }, buttonPressed: { transform: [{ scale: 0.97 }], opacity: 0.9 },
  modalBackdrop: { flex: 1, backgroundColor: "rgba(1,3,2,0.74)", alignItems: "center", justifyContent: "center", padding: 24 }, modalCard: { width: "100%", maxWidth: 420, padding: 22, borderRadius: 26, borderWidth: 1 }, modalMark: { width: 46, height: 46, borderRadius: 15, alignItems: "center", justifyContent: "center", marginBottom: 14 }, modalTitle: { fontSize: 21, lineHeight: 28, fontWeight: "900" }, modalText: { fontSize: 13, lineHeight: 19, marginTop: 4 }, nameInput: { width: "100%", fontSize: 15, lineHeight: 21, paddingHorizontal: 14, height: 52, marginTop: 19, borderRadius: 15, borderWidth: 1 }, modalActions: { width: "100%", justifyContent: "flex-start", gap: 10, marginTop: 20 }, cancel: { paddingHorizontal: 15, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, cancelText: { fontSize: 13, lineHeight: 18, fontWeight: "800" }, confirm: { paddingHorizontal: 18, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, confirmText: { fontSize: 13, lineHeight: 18, fontWeight: "900" },
});
