import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { CoverArt } from "@/components/omniwave/cover-art";
import { Reveal } from "@/components/omniwave/reveal";
import { TrackRow } from "@/components/omniwave/track-row";
import { Waveform } from "@/components/omniwave/waveform";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/omniwave/player-store";
import { useThemeContext } from "@/lib/theme-provider";
import type { Track } from "@/lib/omniwave/types";

function CoverTile({ track, onPress }: { track: Track; onPress: () => void }) {
  const { theme, isRTL } = useThemeContext();
  const align = isRTL ? "right" : "left";
  return <Pressable accessibilityRole="button" accessibilityLabel={track.title} onPress={onPress} style={({ pressed }) => [styles.coverTile, pressed && styles.pressed]}><View style={[styles.coverFrame, { borderColor: `${track.accent}57`, backgroundColor: theme.colors.surface }]}><CoverArt track={track} size={78} showLabel /></View><Text numberOfLines={1} style={[styles.coverTitle, { color: theme.colors.text, textAlign: align }]}>{track.title}</Text><Text numberOfLines={1} style={[styles.coverMeta, { color: theme.colors.muted, textAlign: align }]}>{track.artist}</Text></Pressable>;
}

export default function HomeScreen() {
  const { tracks, playlists, currentTrack, snapshot, playTrack, togglePlay, toggleFavorite, historyIds } = usePlayer();
  const { theme, isRTL, t } = useThemeContext();
  const historyTracks = (historyIds.length ? historyIds.map((id) => tracks.find((track) => track.id === id)).filter(Boolean) : tracks.slice(0, 4)) as Track[];
  const discoveryTracks = tracks.slice(0, 4);
  const favoriteCount = tracks.filter((track) => track.isFavorite).length;
  const direction = isRTL ? "row-reverse" : "row";
  const align = isRTL ? "right" : "left";
  const queueSummary = snapshot.queueLength ? `${snapshot.queueLength} ${t("queueStatus")}` : t("queueStatusEmpty");
  const progress = Math.min(100, Math.max(0, snapshot.durationSeconds ? (snapshot.positionSeconds / snapshot.durationSeconds) * 100 : 0));

  return <ScreenContainer containerClassName="bg-background" className="px-5"><FlatList data={historyTracks} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View>
    <Reveal><View style={[styles.topLine, { flexDirection: direction }]}><Pressable accessibilityRole="button" accessibilityLabel={t("settings")} onPress={() => router.push("/(tabs)/settings" as never)} style={({ pressed }) => [styles.settingsButton, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, pressed && styles.pressed]}><MaterialIcons name="tune" size={20} color={theme.colors.text} /></Pressable><View style={[styles.brandBlock, { alignItems: isRTL ? "flex-end" : "flex-start" }]}><View style={[styles.wordmarkLine, { flexDirection: direction }]}><View style={[styles.brandDot, { backgroundColor: theme.colors.primary }]} /><Text style={[styles.brand, { color: theme.colors.primary, textAlign: align }]}>OMNIWAVE</Text></View><Text style={[styles.heading, { color: theme.colors.text, textAlign: align }]}>{t("appTagline")}</Text></View></View></Reveal>
    <Reveal delay={45}><Pressable accessibilityRole="button" accessibilityLabel={t("nowPlaying")} onPress={() => router.push("/(tabs)/now-playing" as never)} style={({ pressed }) => [styles.sessionCard, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, pressed && styles.pressed]}><View style={[styles.sessionGlowPrimary, { backgroundColor: theme.colors.glow }]} /><View style={[styles.sessionGlowAccent, { backgroundColor: currentTrack?.accent ?? theme.colors.secondary }]} /><View style={[styles.sessionTop, { flexDirection: direction }]}><View style={[styles.liveBadge, { backgroundColor: theme.colors.surfaceMuted }]}><View style={[styles.liveDot, { backgroundColor: snapshot.isPlaying ? theme.colors.primary : theme.colors.muted }]} /><Text style={[styles.liveText, { color: theme.colors.text }]}>{snapshot.isPlaying ? t("playingNow") : t("readyToPlay")}</Text></View><View style={[styles.queueBadge, { backgroundColor: `${theme.colors.primary}16` }]}><MaterialIcons name="queue-music" size={15} color={theme.colors.primary} /><Text numberOfLines={1} style={[styles.queueText, { color: theme.colors.primary }]}>{queueSummary}</Text></View></View><View style={[styles.sessionBody, { flexDirection: direction }]}><View style={[styles.artHalo, { borderColor: `${currentTrack?.accent ?? theme.colors.primary}80` }]}>{currentTrack ? <CoverArt track={currentTrack} size={86} /> : <View style={[styles.emptyArt, { backgroundColor: theme.colors.primary }]}><MaterialIcons name="music-note" size={34} color={theme.colors.onPrimary} /></View>}</View><View style={styles.sessionCopy}><Text numberOfLines={1} style={[styles.sessionTitle, { color: theme.colors.text, textAlign: align }]}>{currentTrack?.title ?? t("library")}</Text><Text numberOfLines={1} style={[styles.sessionArtist, { color: theme.colors.muted, textAlign: align }]}>{currentTrack?.artist ?? t("readyToPlay")}</Text><View style={styles.waveShell}><Waveform color={theme.colors.primary} active={snapshot.isPlaying} /></View></View></View><View style={[styles.progressShell, { backgroundColor: theme.colors.surfaceMuted }]}><View style={[styles.progressValue, { width: `${progress}%`, backgroundColor: theme.colors.primary }]} /></View><View style={[styles.sessionBottom, { flexDirection: direction }]}><Text style={[styles.sessionStatus, { color: theme.colors.muted }]}>{t("session")}</Text><Pressable accessibilityRole="button" accessibilityLabel={snapshot.isPlaying ? t("pause") : t("play")} onPress={(event) => { event.stopPropagation(); togglePlay(); }} style={({ pressed }) => [styles.playButton, { backgroundColor: theme.colors.primary }, pressed && styles.playPressed]}><MaterialIcons name={snapshot.isPlaying ? "pause" : "play-arrow"} size={28} color={theme.colors.onPrimary} /></Pressable></View></Pressable></Reveal>
    <Reveal delay={90}><View style={[styles.quickGrid, { flexDirection: direction }]}><Pressable accessibilityRole="button" accessibilityLabel={t("favorites")} onPress={() => router.push("/(tabs)/library" as never)} style={({ pressed }) => [styles.quickCard, { backgroundColor: theme.colors.surfaceMuted, borderColor: theme.colors.border, alignItems: isRTL ? "flex-end" : "flex-start" }, pressed && styles.pressed]}><View style={[styles.quickIcon, { backgroundColor: `${theme.colors.accent}1F` }]}><MaterialIcons name="favorite" size={19} color={theme.colors.accent} /></View><View><Text style={[styles.quickTitle, { color: theme.colors.text, textAlign: align }]}>{t("favorites")}</Text><Text style={[styles.quickMeta, { color: theme.colors.muted, textAlign: align }]}>{favoriteCount} {t("tracks")}</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t("playlists")} onPress={() => router.push("/(tabs)/playlists" as never)} style={({ pressed }) => [styles.quickCard, { backgroundColor: theme.colors.surfaceMuted, borderColor: theme.colors.border, alignItems: isRTL ? "flex-end" : "flex-start" }, pressed && styles.pressed]}><View style={[styles.quickIcon, { backgroundColor: `${theme.colors.secondary}1F` }]}><MaterialIcons name="queue-music" size={19} color={theme.colors.secondary} /></View><View><Text style={[styles.quickTitle, { color: theme.colors.text, textAlign: align }]}>{t("playlists")}</Text><Text style={[styles.quickMeta, { color: theme.colors.muted, textAlign: align }]}>{playlists.length} {t("playlistsCount")}</Text></View></Pressable></View></Reveal>
    <Reveal delay={125}><View style={[styles.sectionHeader, { flexDirection: direction }]}><Pressable accessibilityRole="button" accessibilityLabel={t("viewLibrary")} onPress={() => router.push("/(tabs)/library" as never)} style={({ pressed }) => [styles.seeAllWrap, { backgroundColor: `${theme.colors.primary}13` }, pressed && styles.pressed]}><Text style={[styles.seeAll, { color: theme.colors.primary }]}>{t("viewLibrary")}</Text><MaterialIcons name={isRTL ? "arrow-back" : "arrow-forward"} size={14} color={theme.colors.primary} /></Pressable><Text style={[styles.sectionTitle, { color: theme.colors.text, textAlign: align }]}>{t("selectedForYou")}</Text></View><View style={[styles.coversRow, { flexDirection: direction }]}>{discoveryTracks.map((track) => <CoverTile key={track.id} track={track} onPress={() => playTrack(track)} />)}</View></Reveal>
    <Reveal delay={155}><View style={[styles.sectionHeader, styles.resumeHeader, { flexDirection: direction }]}><Text style={[styles.sectionLabel, { color: theme.colors.muted }]}>{t("nowPlaying")}</Text><Text style={[styles.sectionTitle, { color: theme.colors.text, textAlign: align }]}>{t("resumeListening")}</Text></View></Reveal>
  </View>} renderItem={({ item }) => <TrackRow track={item} active={item.id === currentTrack?.id} onPress={() => playTrack(item)} onFavorite={() => toggleFavorite(item.id)} />} ItemSeparatorComponent={() => <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 14, paddingBottom: 140 }, topLine: { alignItems: "center", justifyContent: "space-between", marginBottom: 25 }, brandBlock: { flex: 1 }, wordmarkLine: { alignItems: "center", gap: 6 }, brandDot: { width: 6, height: 6, borderRadius: 3 }, brand: { fontSize: 10, lineHeight: 15, fontWeight: "900", letterSpacing: 2.6 }, heading: { fontSize: 31, lineHeight: 40, fontWeight: "900", letterSpacing: -0.55 }, settingsButton: { width: 46, height: 46, borderRadius: 17, alignItems: "center", justifyContent: "center", borderWidth: 1 },
  sessionCard: { minHeight: 282, borderRadius: 31, padding: 19, overflow: "hidden", borderWidth: 1, shadowColor: "#000", shadowOpacity: 0.26, shadowRadius: 23, shadowOffset: { width: 0, height: 11 }, elevation: 7 }, sessionGlowPrimary: { position: "absolute", width: 300, height: 300, borderRadius: 150, right: -154, top: -150, opacity: 0.92 }, sessionGlowAccent: { position: "absolute", width: 150, height: 150, borderRadius: 75, left: -68, bottom: -77, opacity: 0.18 }, sessionTop: { justifyContent: "space-between", alignItems: "center", gap: 8 }, liveBadge: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 13 }, liveDot: { width: 7, height: 7, borderRadius: 4 }, liveText: { fontSize: 11, lineHeight: 15, fontWeight: "900" }, queueBadge: { maxWidth: "55%", flexDirection: "row", alignItems: "center", gap: 5, paddingHorizontal: 9, paddingVertical: 6, borderRadius: 13 }, queueText: { fontSize: 10, lineHeight: 14, fontWeight: "900" }, sessionBody: { alignItems: "center", gap: 16, marginTop: 26 }, artHalo: { padding: 4, borderRadius: 28, borderWidth: 1 }, emptyArt: { width: 86, height: 86, borderRadius: 24, alignItems: "center", justifyContent: "center" }, sessionCopy: { flex: 1, gap: 3, minWidth: 0 }, sessionTitle: { fontSize: 23, lineHeight: 30, fontWeight: "900", letterSpacing: -0.4 }, sessionArtist: { fontSize: 13, lineHeight: 19, fontWeight: "600" }, waveShell: { marginTop: 9, opacity: 0.94 }, progressShell: { height: 4, borderRadius: 3, overflow: "hidden", marginTop: 20 }, progressValue: { height: "100%", borderRadius: 3 }, sessionBottom: { justifyContent: "space-between", alignItems: "center", marginTop: 14 }, sessionStatus: { fontSize: 12, lineHeight: 17, fontWeight: "800" }, playButton: { width: 58, height: 58, borderRadius: 29, alignItems: "center", justifyContent: "center", shadowColor: "#000", shadowOpacity: 0.24, shadowRadius: 10, shadowOffset: { width: 0, height: 5 }, elevation: 5 }, playPressed: { transform: [{ scale: 0.96 }], opacity: 0.92 },
  quickGrid: { gap: 10, marginTop: 14 }, quickCard: { flex: 1, minHeight: 103, borderRadius: 23, padding: 15, borderWidth: 1, justifyContent: "space-between" }, quickIcon: { width: 38, height: 38, borderRadius: 14, alignItems: "center", justifyContent: "center" }, quickTitle: { fontSize: 13, lineHeight: 19, fontWeight: "900" }, quickMeta: { fontSize: 11, lineHeight: 16, marginTop: 1, fontWeight: "600" },
  sectionHeader: { alignItems: "center", justifyContent: "space-between", marginTop: 31, marginBottom: 14 }, sectionTitle: { fontSize: 20, lineHeight: 27, fontWeight: "900", letterSpacing: -0.25 }, sectionLabel: { fontSize: 10, lineHeight: 15, fontWeight: "900", letterSpacing: 0.65 }, seeAllWrap: { minHeight: 35, paddingHorizontal: 11, borderRadius: 12, flexDirection: "row", alignItems: "center", gap: 4 }, seeAll: { fontSize: 11, lineHeight: 16, fontWeight: "900" }, coversRow: { justifyContent: "space-between", gap: 10 }, coverTile: { flex: 1, minWidth: 0 }, coverFrame: { borderRadius: 22, borderWidth: 1, padding: 3, alignSelf: "stretch" }, coverTitle: { fontSize: 11, lineHeight: 16, fontWeight: "900", marginTop: 8 }, coverMeta: { fontSize: 10, lineHeight: 14, fontWeight: "600" }, resumeHeader: { marginTop: 34, marginBottom: 5 }, divider: { height: StyleSheet.hairlineWidth }, pressed: { opacity: 0.74, transform: [{ scale: 0.99 }] },
});
