import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { CollectionSkeleton } from "@/components/omniwave/content-skeleton";
import { CoverArt } from "@/components/omniwave/cover-art";
import { Reveal } from "@/components/omniwave/reveal";
import { TrackRow } from "@/components/omniwave/track-row";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/omniwave/player-store";
import { useThemeContext } from "@/lib/theme-provider";
import type { Track } from "@/lib/omniwave/types";

const FILTERS = ["favorites", "imports", "short", "long"] as const;
const SORTS = ["recent", "title", "artist", "album", "duration"] as const;
type LibraryFilter = (typeof FILTERS)[number];
type LibrarySort = (typeof SORTS)[number];

function normalize(value: string) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase(); }
function compareText(left: string, right: string) { return left.localeCompare(right, undefined, { sensitivity: "base" }); }

function QuickAccessTrack({ track, onPress }: { track: Track; onPress: () => void }) {
  const { theme, isRTL } = useThemeContext();
  return <Pressable accessibilityRole="button" accessibilityLabel={track.title} onPress={onPress} style={({ pressed }) => [styles.quickTrack, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, pressed && styles.pressed]}><CoverArt track={track} size={48} /><View style={styles.quickCopy}><Text numberOfLines={1} style={[styles.quickTrackTitle, { color: theme.colors.text, textAlign: isRTL ? "right" : "left" }]}>{track.title}</Text><Text numberOfLines={1} style={[styles.quickTrackMeta, { color: theme.colors.muted, textAlign: isRTL ? "right" : "left" }]}>{track.artist}</Text></View></Pressable>;
}

export default function LibraryScreen() {
  const { tracks, currentTrack, playTrack, toggleFavorite, addToQueue, importAudioFiles, isReady, isImporting, playbackIssue, clearPlaybackIssue, historyIds } = usePlayer();
  const { theme, isRTL, t } = useThemeContext();
  const [query, setQuery] = useState("");
  const [activeFilters, setActiveFilters] = useState<LibraryFilter[]>([]);
  const [sort, setSort] = useState<LibrarySort>("recent");
  const favoriteTracks = useMemo(() => tracks.filter((track) => track.isFavorite).slice(0, 6), [tracks]);
  const recentTracks = useMemo(() => historyIds.map((id) => tracks.find((track) => track.id === id)).filter((track): track is Track => Boolean(track)).slice(0, 6), [historyIds, tracks]);
  const quickTracks = favoriteTracks.length ? favoriteTracks : recentTracks;
  const quickTitle = favoriteTracks.length ? t("favorites") : t("resumeListening");
  const filteredTracks = useMemo(() => {
    const queryValue = normalize(query.trim());
    const filtered = tracks.filter((track) => {
      const haystack = normalize(`${track.title} ${track.artist} ${track.album} ${track.classification?.genre ?? ""} ${track.classification?.mood ?? ""} ${(track.classification?.tags ?? []).join(" ")}`);
      const matchesQuery = !queryValue || haystack.includes(queryValue);
      const matchesFilters = activeFilters.every((filter) => filter === "favorites" ? track.isFavorite : filter === "imports" ? track.isImported : filter === "short" ? track.durationSeconds > 0 && track.durationSeconds <= 240 : track.durationSeconds >= 241);
      return matchesQuery && matchesFilters;
    });
    return [...filtered].sort((left, right) => sort === "title" ? compareText(left.title, right.title) : sort === "artist" ? compareText(left.artist, right.artist) : sort === "album" ? compareText(left.album, right.album) : sort === "duration" ? left.durationSeconds - right.durationSeconds : 0);
  }, [activeFilters, query, sort, tracks]);
  const align = isRTL ? "right" : "left";
  const direction = isRTL ? "row-reverse" : "row";
  const filterLabels: Record<LibraryFilter, string> = { favorites: t("favorites"), imports: t("yourFiles"), short: t("shortTracks"), long: t("longTracks") };
  const sortLabels: Record<LibrarySort, string> = { recent: t("sortRecent"), title: t("sortTitle"), artist: t("sortArtist"), album: t("sortAlbum"), duration: t("sortDuration") };
  const toggleFilter = (filter: LibraryFilter) => setActiveFilters((previous) => previous.includes(filter) ? previous.filter((item) => item !== filter) : [...previous, filter]);

  if (!isReady) return <ScreenContainer className="px-5"><CollectionSkeleton variant="library" /></ScreenContainer>;

  return <ScreenContainer className="px-5"><FlatList data={filteredTracks} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View>
    <Reveal><View style={[styles.headingRow, { flexDirection: direction }]}><View style={[styles.libraryBadge, { backgroundColor: `${theme.colors.primary}18`, borderColor: `${theme.colors.primary}33` }]}><MaterialIcons name="library-music" size={18} color={theme.colors.primary} /></View><View style={styles.headingCopy}><Text style={[styles.eyebrow, { color: theme.colors.primary, textAlign: align }]}>{t("yourCollection")}</Text><Text style={[styles.heading, { color: theme.colors.text, textAlign: align }]}>{t("library")}</Text></View></View></Reveal>
    {quickTracks.length ? <Reveal delay={35}><View style={styles.quickSection}><View style={[styles.quickSectionHeader, { flexDirection: direction }]}><Text style={[styles.quickSectionMeta, { color: theme.colors.muted }]}>{quickTracks.length} {t("tracks")}</Text><Text style={[styles.quickSectionTitle, { color: theme.colors.text, textAlign: align }]}>{quickTitle}</Text></View><FlatList data={quickTracks} horizontal inverted={isRTL} keyExtractor={(item) => `quick-${item.id}`} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quickList} renderItem={({ item }) => <QuickAccessTrack track={item} onPress={() => playTrack(item)} />} /></View></Reveal> : null}
    <View style={[styles.search, { flexDirection: direction, backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><TextInput value={query} onChangeText={setQuery} placeholder={t("searchPlaceholder")} placeholderTextColor={theme.colors.muted} returnKeyType="done" style={[styles.searchInput, { color: theme.colors.text, textAlign: align }]} /><MaterialIcons name="search" size={21} color={theme.colors.muted} /></View>
    <Reveal delay={50}><View style={[styles.controlCard, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><View style={[styles.controlTitleRow, { flexDirection: direction }]}><MaterialIcons name="filter-list" size={18} color={theme.colors.secondary} /><Text style={[styles.controlTitle, { color: theme.colors.text, textAlign: align }]}>{t("filterLibrary")}</Text>{activeFilters.length ? <Text style={[styles.controlCount, { color: theme.colors.primary }]}>{activeFilters.length} {t("activeFilters")}</Text> : null}</View><View accessibilityRole="radiogroup" style={[styles.chips, { flexDirection: direction }]}><Pressable accessibilityRole="radio" accessibilityState={{ selected: !activeFilters.length }} onPress={() => setActiveFilters([])} style={({ pressed }) => [styles.chip, { backgroundColor: !activeFilters.length ? theme.colors.primary : theme.colors.surfaceMuted, borderColor: !activeFilters.length ? theme.colors.primary : theme.colors.border }, pressed && styles.pressed]}><Text style={[styles.chipText, { color: !activeFilters.length ? theme.colors.onPrimary : theme.colors.muted }]}>{t("all")}</Text></Pressable>{FILTERS.map((value) => { const selected = activeFilters.includes(value); return <Pressable key={value} accessibilityRole="checkbox" accessibilityLabel={filterLabels[value]} accessibilityState={{ checked: selected }} onPress={() => toggleFilter(value)} style={({ pressed }) => [styles.chip, { backgroundColor: selected ? `${theme.colors.primary}18` : theme.colors.surfaceMuted, borderColor: selected ? theme.colors.primary : theme.colors.border }, pressed && styles.pressed]}><Text style={[styles.chipText, { color: selected ? theme.colors.primary : theme.colors.muted }]}>{filterLabels[value]}</Text></Pressable>; })}</View><View style={[styles.controlTitleRow, styles.sortLabel, { flexDirection: direction }]}><MaterialIcons name="sort" size={18} color={theme.colors.secondary} /><Text style={[styles.controlTitle, { color: theme.colors.text, textAlign: align }]}>{t("sortBy")}</Text></View><View accessibilityRole="radiogroup" style={[styles.chips, { flexDirection: direction }]}>{SORTS.map((value) => { const selected = sort === value; return <Pressable key={value} accessibilityRole="radio" accessibilityLabel={sortLabels[value]} accessibilityState={{ selected }} onPress={() => setSort(value)} style={({ pressed }) => [styles.chip, { backgroundColor: selected ? theme.colors.secondary : theme.colors.surfaceMuted, borderColor: selected ? theme.colors.secondary : theme.colors.border }, pressed && styles.pressed]}><Text style={[styles.chipText, { color: selected ? theme.colors.onPrimary : theme.colors.muted }]}>{sortLabels[value]}</Text></Pressable>; })}</View></View></Reveal>
    <View style={[styles.importCard, { backgroundColor: theme.colors.surface, borderColor: playbackIssue === "import" ? theme.colors.accent : theme.colors.border }]}><View style={[styles.importContent, { flexDirection: direction }]}><View style={[styles.importIcon, { backgroundColor: theme.colors.primary }]}><MaterialIcons name="add-to-queue" size={22} color={theme.colors.onPrimary} /></View><View style={styles.importCopy}><Text style={[styles.importTitle, { color: theme.colors.text, textAlign: align }]}>{t("addYourAudio")}</Text><Text style={[styles.importText, { color: playbackIssue === "import" ? theme.colors.accent : theme.colors.muted, textAlign: align }]}>{isImporting ? t("importing") : playbackIssue === "import" ? t("importFailed") : t("preferencesSaved")}</Text></View></View><Pressable accessibilityRole="button" accessibilityLabel={playbackIssue === "import" ? t("tryAgain") : t("addFiles")} accessibilityState={{ busy: isImporting }} disabled={isImporting} onPress={() => { clearPlaybackIssue(); void importAudioFiles(); }} style={({ pressed }) => [styles.importButton, { backgroundColor: theme.colors.primary, flexDirection: direction }, isImporting && styles.disabled, pressed && styles.buttonPressed]}>{isImporting ? <ActivityIndicator size="small" color={theme.colors.onPrimary} /> : <><Text style={[styles.importButtonText, { color: theme.colors.onPrimary }]}>{playbackIssue === "import" ? t("tryAgain") : t("addFiles")}</Text><MaterialIcons name={playbackIssue === "import" ? "refresh" : "add"} size={18} color={theme.colors.onPrimary} /></>}</Pressable></View>
    <View style={[styles.listHeader, { flexDirection: direction }]}><Text style={[styles.count, { color: theme.colors.muted }]}>{`${filteredTracks.length} ${t("tracks")}`}</Text><Text style={[styles.listTitle, { color: theme.colors.text, textAlign: align }]}>{t("tracks")}</Text></View>
  </View>} renderItem={({ item }) => <TrackRow track={item} active={item.id === currentTrack?.id} onPress={() => playTrack(item)} onFavorite={() => toggleFavorite(item.id)} onQueue={() => addToQueue(item.id)} />} ItemSeparatorComponent={() => <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />} ListEmptyComponent={<View style={styles.empty}><View style={[styles.emptyIcon, { backgroundColor: theme.colors.surfaceMuted }]}><MaterialIcons name="music-off" size={26} color={theme.colors.muted} /></View><Text style={[styles.emptyTitle, { color: theme.colors.text }]}>{t("noResults")}</Text><Text style={[styles.emptyText, { color: theme.colors.muted }]}>{t("noResultsHint")}</Text></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 12, paddingBottom: 132 }, headingRow: { alignItems: "center", justifyContent: "flex-start", gap: 12, marginBottom: 20 }, headingCopy: { flex: 1 }, eyebrow: { fontSize: 10, lineHeight: 15, fontWeight: "900", letterSpacing: 1.9 }, heading: { fontSize: 30, lineHeight: 38, fontWeight: "900" }, libraryBadge: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 1 },
  quickSection: { marginBottom: 20 }, quickSectionHeader: { alignItems: "center", justifyContent: "space-between", marginBottom: 10 }, quickSectionTitle: { fontSize: 17, lineHeight: 23, fontWeight: "900" }, quickSectionMeta: { fontSize: 10, lineHeight: 15, fontWeight: "800" }, quickList: { gap: 9 }, quickTrack: { width: 174, minHeight: 70, padding: 10, borderRadius: 18, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 9 }, quickCopy: { flex: 1, minWidth: 0 }, quickTrackTitle: { fontSize: 12, lineHeight: 17, fontWeight: "900" }, quickTrackMeta: { fontSize: 10, lineHeight: 14, marginTop: 1 },
  search: { height: 52, alignItems: "center", gap: 10, paddingHorizontal: 15, borderRadius: 17, borderWidth: 1 }, searchInput: { flex: 1, height: "100%", fontSize: 14, lineHeight: 20 }, controlCard: { marginTop: 12, padding: 13, borderRadius: 20, borderWidth: 1 }, controlTitleRow: { alignItems: "center", gap: 7 }, controlTitle: { flex: 1, fontSize: 12, lineHeight: 18, fontWeight: "900" }, controlCount: { fontSize: 10, lineHeight: 15, fontWeight: "800" }, chips: { gap: 7, flexWrap: "wrap", marginTop: 10 }, chip: { minHeight: 36, paddingHorizontal: 11, paddingVertical: 7, borderRadius: 13, borderWidth: 1, alignItems: "center", justifyContent: "center" }, chipText: { fontSize: 11, lineHeight: 15, fontWeight: "800" }, sortLabel: { marginTop: 16 },
  importCard: { padding: 16, borderRadius: 22, borderWidth: 1, marginTop: 14, marginBottom: 24 }, importContent: { alignItems: "center", gap: 12 }, importIcon: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center" }, importCopy: { flex: 1 }, importTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, importText: { fontSize: 12, lineHeight: 18, marginTop: 2 }, importButton: { minHeight: 40, marginTop: 14, borderRadius: 13, gap: 4, alignItems: "center", justifyContent: "center" }, importButtonText: { fontSize: 12, lineHeight: 16, fontWeight: "900" }, disabled: { opacity: 0.64 },
  listHeader: { justifyContent: "space-between", alignItems: "center", marginBottom: 3 }, listTitle: { fontSize: 19, lineHeight: 26, fontWeight: "900" }, count: { fontSize: 12, lineHeight: 17, fontWeight: "700" }, divider: { height: StyleSheet.hairlineWidth }, empty: { paddingVertical: 52, alignItems: "center" }, emptyIcon: { width: 54, height: 54, borderRadius: 18, alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900", marginTop: 14 }, emptyText: { fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 4 }, pressed: { opacity: 0.7 }, buttonPressed: { transform: [{ scale: 0.98 }], opacity: 0.92 },
});
