import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { CoverArt } from "@/components/omniwave/cover-art";
import { TrackRow } from "@/components/omniwave/track-row";
import { ScreenContainer } from "@/components/screen-container";
import { formatTime } from "@/lib/omniwave/data";
import { usePlayer } from "@/lib/omniwave/player-store";
import { useThemeContext } from "@/lib/theme-provider";

const TIMER_OPTIONS = [0, 15, 30, 45, 60] as const;

export default function ToolsScreen() {
  const { tracks, queueTracks, currentTrack, snapshot, toggleFavorite, addToQueue, removeFromQueue, moveQueueTrack, clearQueue, playQueueTrack, setSleepTimer, stopPlaybackNow } = usePlayer();
  const { theme, isRTL, t } = useThemeContext();
  const align = isRTL ? "right" : "left";
  const direction = isRTL ? "row-reverse" : "row";
  const recommendations = tracks.filter((track) => track.id !== currentTrack?.id && !queueTracks.some((queued) => queued.id === track.id)).slice(0, 3);
  const remainingMinutes = snapshot.sleepTimerRemainingSeconds ? Math.ceil(snapshot.sleepTimerRemainingSeconds / 60) : 0;

  return <ScreenContainer className="px-5"><FlatList data={queueTracks} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<View>
    <View style={styles.headingBlock}><Text style={[styles.eyebrow, { color: theme.colors.primary, textAlign: align }]}>{t("quickControls")}</Text><Text style={[styles.heading, { color: theme.colors.text, textAlign: align }]}>{t("tools")}</Text></View>
    <View style={[styles.timerCard, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><View style={[styles.timerTop, { flexDirection: direction }]}><View style={[styles.timerIcon, { backgroundColor: `${theme.colors.secondary}22` }]}><MaterialIcons name="bedtime" size={22} color={theme.colors.secondary} /></View><View style={styles.timerCopy}><Text style={[styles.cardTitle, { color: theme.colors.text, textAlign: align }]}>{t("sleepTimer")}</Text><Text style={[styles.cardText, { color: theme.colors.muted, textAlign: align }]}>{snapshot.sleepTimerEndsAt ? `${t("sleepTimerActive")} ${remainingMinutes} ${t("minutes")}` : t("off")}</Text></View></View><View style={[styles.timerChoices, { flexDirection: direction }]}>{TIMER_OPTIONS.map((minutes) => { const active = minutes === 0 ? !snapshot.sleepTimerEndsAt : Boolean(snapshot.sleepTimerEndsAt && remainingMinutes <= minutes && remainingMinutes > minutes - 2); return <Pressable key={minutes} onPress={() => setSleepTimer(minutes)} style={({ pressed }) => [styles.timerChoice, { backgroundColor: active ? theme.colors.primary : theme.colors.surfaceMuted, borderColor: active ? theme.colors.primary : theme.colors.border }, pressed && styles.pressed]}><Text style={[styles.timerChoiceText, { color: active ? theme.colors.onPrimary : theme.colors.muted }]}>{minutes ? `${minutes} ${t("minutes")}` : t("off")}</Text></Pressable>; })}</View>{snapshot.sleepTimerEndsAt ? <Pressable onPress={stopPlaybackNow} style={({ pressed }) => [styles.stopButton, { borderColor: `${theme.colors.accent}99`, flexDirection: direction }, pressed && styles.pressed]}><MaterialIcons name="stop-circle" size={18} color={theme.colors.accent} /><Text style={[styles.stopText, { color: theme.colors.accent }]}>{t("stopNow")}</Text></Pressable> : null}</View>
    <View style={[styles.queueHeader, { flexDirection: direction }]}>{queueTracks.length ? <Pressable onPress={clearQueue}><Text style={[styles.clearText, { color: theme.colors.accent }]}>{t("clearQueue")}</Text></Pressable> : <View />}<Text style={[styles.sectionTitle, { color: theme.colors.text, textAlign: align }]}>{t("queue")} · {queueTracks.length}</Text></View>
    {!queueTracks.length ? <View style={[styles.emptyCard, { backgroundColor: theme.colors.surfaceMuted, borderColor: theme.colors.border }]}><View style={[styles.emptyIcon, { backgroundColor: `${theme.colors.primary}1A` }]}><MaterialIcons name="queue-music" size={28} color={theme.colors.primary} /></View><Text style={[styles.emptyTitle, { color: theme.colors.text }]}>{t("queueEmpty")}</Text><Text style={[styles.emptyText, { color: theme.colors.muted }]}>{t("queueEmptyHint")}</Text></View> : null}
    <Text style={[styles.recommendTitle, { color: theme.colors.muted, textAlign: align }]}>{t("selectedForYou")}</Text>
    <View style={[styles.recommendations, { flexDirection: direction }]}>{recommendations.map((track) => <Pressable key={track.id} onPress={() => addToQueue(track.id)} style={({ pressed }) => [styles.recommendation, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }, pressed && styles.pressed]}><CoverArt track={track} size={42} /><View style={styles.recommendCopy}><Text numberOfLines={1} style={[styles.recommendName, { color: theme.colors.text, textAlign: align }]}>{track.title}</Text><Text numberOfLines={1} style={[styles.recommendArtist, { color: theme.colors.muted, textAlign: align }]}>{track.artist}</Text></View><MaterialIcons name="add" size={20} color={theme.colors.primary} /></Pressable>)}</View>
  </View>} renderItem={({ item, index }) => <TrackRow track={item} active={item.id === currentTrack?.id} onPress={() => playQueueTrack(item.id)} onFavorite={() => toggleFavorite(item.id)} trailing={<View style={[styles.queueActions, { flexDirection: direction }]}><Pressable accessibilityRole="button" accessibilityLabel={t("moveUp")} disabled={index === 0} onPress={() => moveQueueTrack(item.id, -1)} style={({ pressed }) => [styles.actionButton, index === 0 && styles.disabledAction, pressed && styles.pressed]}><MaterialIcons name="arrow-upward" size={18} color={theme.colors.muted} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t("moveDown")} disabled={index === queueTracks.length - 1} onPress={() => moveQueueTrack(item.id, 1)} style={({ pressed }) => [styles.actionButton, index === queueTracks.length - 1 && styles.disabledAction, pressed && styles.pressed]}><MaterialIcons name="arrow-downward" size={18} color={theme.colors.muted} /></Pressable><Pressable accessibilityRole="button" accessibilityLabel={t("remove")} onPress={() => removeFromQueue(item.id)} style={({ pressed }) => [styles.actionButton, pressed && styles.pressed]}><MaterialIcons name="close" size={20} color={theme.colors.accent} /></Pressable></View>} />} ItemSeparatorComponent={() => <View style={[styles.divider, { backgroundColor: theme.colors.border }]} />} ListFooterComponent={queueTracks.length ? <Text style={[styles.footer, { color: theme.colors.muted }]}>{formatTime(snapshot.durationSeconds)}</Text> : null} /></ScreenContainer>;
}

const styles = StyleSheet.create({
  content: { paddingTop: 12, paddingBottom: 132 }, headingBlock: { marginBottom: 18 }, eyebrow: { fontSize: 10, lineHeight: 15, fontWeight: "900", letterSpacing: 1.9 }, heading: { fontSize: 30, lineHeight: 38, fontWeight: "900" }, timerCard: { padding: 16, borderRadius: 22, borderWidth: 1 }, timerTop: { alignItems: "center", gap: 12 }, timerIcon: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center" }, timerCopy: { flex: 1 }, cardTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, cardText: { fontSize: 12, lineHeight: 18, marginTop: 2 }, timerChoices: { gap: 7, flexWrap: "wrap", marginTop: 15 }, timerChoice: { borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8, borderRadius: 13 }, timerChoiceText: { fontSize: 11, lineHeight: 16, fontWeight: "800" }, stopButton: { marginTop: 13, minHeight: 38, borderWidth: 1, borderRadius: 12, alignItems: "center", justifyContent: "center", gap: 5 }, stopText: { fontSize: 12, lineHeight: 17, fontWeight: "900" },
  queueHeader: { alignItems: "center", justifyContent: "space-between", marginTop: 27, marginBottom: 7 }, sectionTitle: { fontSize: 19, lineHeight: 26, fontWeight: "900" }, clearText: { fontSize: 12, lineHeight: 17, fontWeight: "800" }, emptyCard: { marginTop: 4, padding: 20, borderRadius: 21, borderWidth: 1, alignItems: "center" }, emptyIcon: { width: 54, height: 54, borderRadius: 18, alignItems: "center", justifyContent: "center" }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900", marginTop: 12 }, emptyText: { fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 4 }, recommendTitle: { marginTop: 24, marginBottom: 9, fontSize: 11, lineHeight: 16, letterSpacing: 1.2, fontWeight: "900" }, recommendations: { gap: 8 }, recommendation: { flex: 1, padding: 9, borderRadius: 17, borderWidth: 1, alignItems: "center", gap: 8 }, recommendCopy: { flex: 1, minWidth: 0 }, recommendName: { fontSize: 11, lineHeight: 16, fontWeight: "800" }, recommendArtist: { fontSize: 10, lineHeight: 14 }, queueActions: { alignItems: "center", gap: 1 }, actionButton: { width: 32, height: 32, borderRadius: 16, alignItems: "center", justifyContent: "center" }, disabledAction: { opacity: 0.3 }, divider: { height: StyleSheet.hairlineWidth }, footer: { fontSize: 11, lineHeight: 16, textAlign: "center", marginTop: 12 }, pressed: { opacity: 0.7 },
});
